version: '3.8'

services:
  rds:
    image: 664418977283.dkr.ecr.us-east-1.amazonaws.com/prod-rds
    container_name: backend_rds
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_rds.settings
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

  redis:
    image: 664418977283.dkr.ecr.us-east-1.amazonaws.com/prod-redis
    container_name: backend_redis
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_redis.settings
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

  frontend:
    image: 664418977283.dkr.ecr.us-east-1.amazonaws.com/prod-frontend
    container_name: frontend_app
    restart: always
    ports:
      - "8003:8003"
    environment:
      - DJANGO_SETTINGS_MODULE=frontend_app.settings
      - API_URL=${API_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}